- name: Przygotowanie środowiska
  include_tasks: prepare_env.yaml

- name: Pobranie paczki
  include_role: 
    name: common
    tasks_from: get_files.yaml

#- name: Sprawdzenie wymagań
#  include_tasks: check_prerequisits.yaml
  
- name: Uruchomienie serwisu
  include_tasks: manage_service.yaml