- name: Przygotowanie środowiska
  include_tasks: prepare_env.yaml

- name: Stop/stworzenie serwisu
  include_tasks: manage_service.yaml
  vars:
    serwis_status: stopped

- name: Konfiguracja GCP SDK
  include_role: 
    name: common
    tasks_from: config_gcp.yaml

- name: Pobranie paczki
  include_role: 
    name: common
    tasks_from: get_files.yaml

- name: Uruchomienie serwisu
  include_tasks: manage_service.yaml
  vars:
    serwis_status: started