- name: Create service directory
  win_file:
    path: "{{ dest_path }}"
    state: directory

- name: Create temp directory
  win_file:
    path: C:\temp
    state: directory

- name: Create prerequisits directory
  win_file:
    path: C:\prerequisits
    state: directory

- name: Create log directory
  win_file:
    path: "{{ logs_path }}"
    state: directory

- name: Check if GCP SDK is installed
  win_shell: gcloud --version
  ignore_errors: true
  register: gcp_sdk

- name: Install SDK
  include_role:
    name: common
    tasks_from: install_gcp_sdk.yaml
  when: gcp_sdk.rc != 0

- name: Download installer
  win_shell: |
    gcloud storage cp gs://olomg-bucket/prerequisits_serwis/dotnet9.exe C:\prerequisits\dotnet9.0.3.exe

- name: Zainstaluj .NET 9.0 Runtime
  win_package:
    path: C:\\prerequisits\dotnet9.0.3.exe
    arguments: "/quiet"
    state: present
    product_id: '{c8760728-04a2-4c48-b207-61c8dc98f639}'
    




