- name: Create service directory
  win_file:
    path: "{{ dest_path }}"
    state: directory

- name: Create prerequisits directory
  win_file:
    path: C:\prerequisits
    state: directory

- name: Create log directory
  win_file:
    path: "{{ logs_path }}"
    state: directory

- name: Check if authenticated
  win_shell: gcloud auth list --filter=status:ACTIVE --format="value(account)"
  register: gcp_auth

- name: Konfiguracja GCP SDK
  include_role: 
    name: common
    tasks_from: config_gcp.yaml
  when: gcp_auth.stdout == ""

- name: Install prerequisits
  include_tasks: install_prereq.yaml
  loop: "{{ prerequisits }}"
  loop_control:
    loop_var: prereq


    




