- name: Create service directory
  win_file:
    path: "{{ dest_path }}"
    state: directory

- name: Create log directory
  win_file:
    path: "{{ logs_path }}"
    state: directory

- name: Check if GCP SDK is installed
  win_shell: gcloud --version
  ignore_errors: true
  register: gcp_sdk

- name: Install SDK
  include_role:
    name: common
    tasks_from: install_gcp_sdk.yaml
  when: gcp_sdk.rc != 0