- name: Create service directory
  win_file:
    path: "{{ dest_path }}"
    state: directory

- name: Create prerequisits directory
  win_file:
    path: C:\prerequisits
    state: directory

- name: Create log directory
  win_file:
    path: "{{ logs_path }}"
    state: directory

- name: Check if authenticated
  win_shell: gcloud auth list --filter=status:ACTIVE --format="value(account)"
  register: gcp_auth

- name: Konfiguracja GCP SDK
  include_role: 
    name: common
    tasks_from: config_gcp.yaml
  when: gcp_auth.stdout == ""

- name: Download installer
  win_shell: |
    gcloud storage cp gs://olomg-bucket/prerequisits_serwis/dotnet9.0.3.exe C:\prerequisits\dotnet9.0.3.exe

- name: Zainstaluj .NET 9.0 Runtime
  win_package:
    path: C:\\prerequisits\dotnet9.0.3.exe
    arguments: "/quiet"
    state: present
    product_id: '{c8760728-04a2-4c48-b207-61c8dc98f639}'
    




