- name: Przygotowanie środowiska
  include_tasks: prepare_env.yaml

- name: Stop/stworzenie pooli i site
  include_tasks: manage_iis.yaml
  vars:
    pool_status: stopped

- name: Pobranie paczki
  include_role: 
    name: common
    tasks_from: get_files.yaml
  vars:
    download_dest_path: "{{ dest_path }}"

- name: Uruchomienie serwisu
  include_tasks: manage_iis.yaml
  vars:
    pool_status: started