- name: Download SA key
  win_get_url: 
    url: "{{ json_url }}"
    dest: "C:\\temp\\{{ json_name }}"

- name: Skonfiguruj autoryzację GCP z pliku JSON
  win_shell: |
    gcloud auth activate-service-account --key-file="C:\\temp\\{{ json_name }}"

- name: sprzątanie
  win_file:
    path: "C:\\temp\\{{ json_name }}"
    state: absent