- name: Check if authenticated
  win_shell: gcloud auth list --filter=status:ACTIVE --format="value(account)"
  register: gcp_auth
- name: Skonfiguruj autoryzację GCP z pliku JSON
  win_shell: |
    gcloud auth activate-service-account --key-file="C:\temp\central-apex-450419-r2-b716b5e92620.json"
  when: gcp_auth.stdout == ""

- name: sprzątanie
  win_file:
    path: C:\temp\central-apex-450419-r2-b716b5e92620.json
    state: absent
  when: gcp_auth.stdout == ""