- name: Pobierz instalator Google Cloud SDK
  win_get_url:
    url: "https://dl.google.com/dl/cloudsdk/channels/rapid/GoogleCloudSDKInstaller.exe"
    dest: "C:\\temp\\GoogleCloudSDKInstaller.exe"

- name: Uruchom instalator Google Cloud SDK
  win_package:
    path: "C:\\temp\\GoogleCloudSDKInstaller.exe"
    arguments: "/S"
    state: present

- name: Dodaj Google Cloud SDK do zmiennej PATH (Windows)
  win_environment:
    name: PATH
    value: "C:\\Program Files (x86)\\Google\\Cloud SDK\\google-cloud-sdk\\bin"
    state: present
    level: machine

