- hosts: all
  gather_facts: no
  tasks:
    - name: Config gcp
      include_role:
        name: common
        tasks_from: config_gcp.yaml

- hosts: service
  gather_facts: no
  tasks:
    - name: Deploy service
      include_role: 
        name: DeployService

- hosts: iis
  gather_facts: no
  tasks:
    - name: Deploy webstie
      include_role: 
        name: DeployIIS